name: Build and Deploy Streamlit app on ec2 instance

on:
  push:
    branches: ["main"]


jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
    # bucket name, region, cloudfront distribution id
      BUCKET: oluwaseunadeyo.com.ng
      REGION: eu-west-1
      DIST_ID: EWF2XRZWNJ64E

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Copy files to S3
      run: |
      chmod 400 testkey.pem  
      ssh -i "testkey.pem" ubuntu@ec2-52-201-250-185.compute-1.amazonaws.com
   
    - name: Invalidate cloudfront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"